structure/web/views.py
import atexit
import csv
import os
from os import environ
from uuid import uuid4
import secrets
from random import randint, choice
import string
import requests
from requests.auth import HTTPBasicAuth
# from apscheduler.schedulers.background import BackgroundScheduler
from flask import render_template, Blueprint, session, redirect, url_for, jsonify, current_app, request
from flask_login import login_required
from sqlalchemy import and_, or_, desc
from flask_mail import Mail, Message
from datetime import date,datetime
from structure import db,mail ,photos,app
from structure.core.forms import FilterForm,SipRequestForm , IssueForm,NumberSearchForm,ExtForm
from structure.about.forms import AboutForm
from structure.web.forms import SearchForm ,AddFoodsForm
from structure.models import User  , Category , Restaurant , Food ,Comment
from werkzeug.utils import secure_filename
from PIL import Image
# import pytesseract 
# from io import BytesIO
import base64
from faker import Faker

web = Blueprint('web', __name__)
fake = Faker()

def encode_image(image_path):
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode('utf-8')

@web.route("/food/imageadd", methods=['GET', 'POST'])
def imageadd():
    api_key = os.environ.get('API_KEY')
    form = AboutForm()
    form2 = AddFoodsForm()
    categories = Category.query.all()
    restaurants = Restaurant.query.all()
    if request.method == 'POST':
        img = request.files.get('images')
        image_path = os.path.join(app.config['UPLOADED_PHOTOS_DEST'], img.filename)
        img.save(image_path)

        # Encode the image to base64
        base64_image = encode_image(image_path)

        # Send the image to the GPT-4 Vision API
        api_url = 'https://api.openai.com/v1/chat/completions'
        headers = {
            'Authorization': f'Bearer {api_key}',
            'Content-Type': 'application/json'
        }

        payload = {
            "model": "gpt-4-vision-preview",
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": "Extract all menu items, categories, and prices as a list .Eg Food Name, Price, Category/Type"
                        },
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/jpeg;base64,{base64_image}"
                            }
                        }
                    ]
                }
            ],
            "max_tokens": 300
        }

        response = requests.post(api_url, headers=headers, json=payload)
        response_data = response.json()
        # response_data = 

        if 'error' in response_data:
            print(f"Error: {response_data['error']}")
        
        # Parse the GPT-4 Vision API response
        menu_items = response_data.get('choices', [])
        print(menu_items)
        # # Parse the ChatGPT API response
        menu_items = []

        for message in response_data['choices'][0]['message']['content'].split('\n'):
            # Assuming each line in the response contains an item, category, and price separated by commas
            item_data = message.split(',')
            menu_items.append(item_data)
            print(item_data)
        # return(menu_items)
        return render_template('web/addfood2.html', menu_items=menu_items,form =form2, categories =categories ,restaurants =restaurants)

    return render_template('web/addfood2.html', form=form)



@web.route('/')
def index():
    form = SearchForm()
    per_page = 40
    page = request.args.get('page', default=1, type=int)
    restaurants_query = Restaurant.query.paginate(page=page, per_page=per_page, error_out=False)
    return render_template('web/index.html', restaurants=restaurants_query,form=form)

@web.route('/restaurants')
def restaurants():
    per_page = 40
    page = request.args.get('page', default=1, type=int)
    restaurants_query = Restaurant.query.all()
    return render_template('web/restaurants.html', restaurants=restaurants_query)

@web.route('/restaurant/<int:id>')
def restaurant(id):
    restaurant = Restaurant.query.filter_by(id=id).first()
    foods = Food.query.filter_by(restaurant_id=id).all()

    return render_template('web/restaurant.html', restaurant=restaurant,foods=foods)

@web.route('/filters', methods=['GET', 'POST'])
def filter_page():
    form = SearchForm(request.form)

    if request.method == 'POST':
        # Build the query based on the form inputs
        query = Restaurant.query.join(Food)
        print(form.food_name.data)
        print(form.restaurant_name.data)
        if form.food_name.data:
            query = query.filter(Food.name.ilike(f"%{form.food_name.data}%"))

        if form.restaurant_name.data:
            query = query.filter(Restaurant.name.ilike(f"%{form.restaurant_name.data}%"))

        if form.min_price.data is not None:
            query = query.filter(Food.price >= form.min_price.data)

        if form.max_price.data is not None:
            query = query.filter(Food.price <= form.max_price.data)

        restaurants = query.all()
    else:
        # If no form submission, show all restaurants
        restaurants = Restaurant.query.all()
    
    print(restaurants)

    return render_template('web/filter.html', form=form, restaurants=restaurants)

@web.route('/search',methods=['GET', 'POST'])
def search():
    form = SearchForm()
    filtered = "no"
    if request.method=="POST":
        filtered = "yes"
        print(request.form.get('type') )
        if request.form.get('type') == "food":
            
            food = request.form.get('text')
            # Build the SQLAlchemy filter conditions
            conditions = []
            if food:
                # Build a list of conditions that match the location field
                # using the LIKE operator and the % wildcard
                food_conditions = [
                    Food.name.like(f"%{food}%"),
                    Food.name.like(f"{food}%"),
                    Food.name.like(f"%{food}"),
                ]
                # Use the OR operator to combine the conditions into a single
                # condition that matches any of the location variations
                conditions.append(or_(*food_conditions))
                # conditions.append(or_(Delivery.start_date.between(date_min, date_max),Delivery.end_date.between(date_min, date_max)))
            print(conditions[0])
            foods = Food.query.filter(and_(*conditions)).all()
            print(foods)
            return render_template("web/foodfilter.html", foods=foods,form=form ,filtered=filtered)
        elif request.form.get('type') == "restaurant":
            print("searching...")
            # Get the filter values from the form
            restaurant = Restaurant.query.all()
            text = request.form.get('text')
            print(text)
            # # Build the SQLAlchemy filter conditions
            conditions = []
            if restaurant:
                restaurants =Restaurant.query.filter(Restaurant.name.like(f"%{text}%")).all()
                # Build a list of conditions that match the location field
                # using the LIKE operator and the % wildcard
            #     restaurant_conditions = [
            #         Restaurant.name.like(f"%{text}%")
            #     ]
            #     # Use the OR operator to combine the conditions into a single
            #     # condition that matches any of the restaurant variations
            #     conditions.append(or_(*restaurant_conditions))
            # restaurants = Restaurant.query.filter(and_(*conditions)).all()
            print("restaurants")
            print(restaurants)
            return render_template("web/filter.html",form=form,restaurants=restaurants, filtered = filtered)


@web.route('/filter',methods=['GET', 'POST'])
def filter():
    form = SearchForm()
    restaurant = Restaurant.query.all()
    # destinations = Destination.query.all()
    # user =User.query.filter_by(id=session['id'])
    if request.method == "POST":
        print("searching...")
        # Get the filter values from the form
        text = form.restaurant_name.data
        # # Build the SQLAlchemy filter conditions
        conditions = []
        if restaurant:
            # Build a list of conditions that match the location field
            # using the LIKE operator and the % wildcard
            location_conditions = [
                Restaurant.name.like(f"%{text}%")
            ]
            # Use the OR operator to combine the conditions into a single
            # condition that matches any of the location variations
            conditions.append(or_(*location_conditions))
        restaurants = Restaurant.query.filter(and_(*conditions)).all()
        return render_template("web/filter.html",form=form,restaurants=restaurants)

    return render_template('web/filter.html',form=form)

@web.route('/foodfilter',methods=['GET', 'POST'])
def foodfilter():
    filterform = SearchForm()
    # foods = Food.query.all()
    filtered = "no"
    if request.method == "POST":
        print("searching...")
        # Get the filter values from the form
        filtered = "yes"
        food = filterform.food_name.data
        price_min = filterform.min_price.data
        price_max = filterform.max_price.data
        # Build the SQLAlchemy filter conditions
        conditions = []
        if food:
            # Build a list of conditions that match the location field
            # using the LIKE operator and the % wildcard
            food_conditions = [
                Food.name.like(f"%{food}%"),
                Food.name.like(f"{food}%"),
                Food.name.like(f"%{food}"),
            ]

structure/templates/web/addfood.html
{% extends "web/base.html" %}
{% block content %}
   
    <!-- Content ================================================== -->
    <div class="container margin_60_35">
        <div class="row">
            
            <div class="col-lg-12">
                <div class="box_style_2">
                    <h2 class="inner">Add Foods</h2>
                    

                   
              <!-- End box_style_1 -->
      
  
        <form method="post">
            {{ form.csrf_token }}
            {{ form.hidden_tag() }}
        
            {{ form.restaurant.label }} 
            <select class="!border-0 !rounded-md lg:w-1/2 w-full" name="restaurant">
                <option>Choose a restaurant</option>
                {% for restaurant in restaurants %}
                <option value="{{restaurant.id}}"><span>{{restaurant.name}}</i> </span></option>
                {% endfor %}
            </select>
            
            <div id="foods-container">
                {% for i in range(form.foods.entries|length) %}
                <div class="food-row ">
                    <div class="row">
                    <div class=" col-md-3">
                        <div class="form-group">
                        <label>Name</label>
                        <input type="text" name="name-{{ i }}" class="form-control" required>
                    </div>
                </div>
                    <div class=" col-md-2">
                        <div class="form-group">
                    <label>Price</label>
                    <input type="integer" name="price-{{ i }}" class="form-control" required>
</div>
</div>
<div class="col-md-2">
    <div class="form-group">
                    {{ form.foods.entries[i].category.label }}
                    <select name="foods-{{ i }}-category" class="form-control" required>
                        <option>Choose a category</option>
                        {% for category in categories %}
                        <option value="{{category.id}}"><span>{{category.name}}</span></option>
                        {% endfor %}
                    </select>
                    </div>
                </div>
        
                    <button type="button" class="btn btn-danger m-4 remove-food">-</button>
                </div>
            </div>
                {% endfor %}
            </div>
        <div class="row">
            <button type="button" class="btn btn-success m-3" id="add-food">+</button>
            </div>
            {{ form.submit }}
          </form>

    </div><!-- End container -->
    <!-- End Content =============================================== -->
    <script>
        // JavaScript code to dynamically add and remove food rows
        document.addEventListener('DOMContentLoaded', function () {
            const foodsContainer = document.getElementById('foods-container');
            const addFoodButton = document.getElementById('add-food');
    
            addFoodButton.addEventListener('click', function () {
                const template = document.querySelector('.food-row');
                const clone = template.cloneNode(true);
    
                // Generate unique names for the cloned form fields
                const index = foodsContainer.childElementCount;
                clone.querySelectorAll('input, select').forEach(field => {
                    const originalName = field.getAttribute('name');
                    if (originalName) {
                        // Update the index in the name, price, and category attributes
                        const newName = originalName.replace(/-(\d+)/, `-${index}`);
                        field.setAttribute('name', newName);
                    }
                });
    
                clone.querySelector('.remove-food').addEventListener('click', function () {
                    clone.remove();
                });
    
                foodsContainer.appendChild(clone);
            });
        });
    </script>

    
{%endblock%}

structure/templates/web/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="pizza, delivery food, fast food, sushi, take away, chinese, italian food">
    <meta name="description" content="">
    <meta name="tsl" content="Ansonika">
    <title>Food Directory</title>

    <!-- Favicons-->
    <link rel="shortcut icon" href="/static/quickfood/img/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" href="/static/quickfood/img/apple-touch-icon-57x57-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="/static/quickfood/img/apple-touch-icon-72x72-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="/static/quickfood/img/apple-touch-icon-114x114-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="/static/quickfood/img/apple-touch-icon-144x144-precomposed.png">
    
    <!-- GOOGLE WEB FONT -->
    <link href="../css2?family=Gochi+Hand&family=Lato:wght@300;400;700;900&display=swap" rel="stylesheet">

    <!-- BASE CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='quickfood/css/animate.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='quickfood/css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='quickfood/css/menu.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='quickfood/css/style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='quickfood/css/responsive.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='quickfood/css/elegant_font/elegant_font.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='quickfood/css/fontello/css/style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='quickfood/css/magnificent-popup.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='quickfood/css/pop_up.css') }}">

    <!-- <link href="css/animate.min.css" rel="stylesheet">
	<link href="css/bootstrap.min.css" rel="stylesheet">
	<link href="css/menu.css" rel="stylesheet">
	<link href="css/style.css" rel="stylesheet">
	<link href="css/responsive.css" rel="stylesheet">
	<link href="css/elegant_font/elegant_font.min.css" rel="stylesheet">
	<link href="css/fontello/css/fontello.min.css" rel="stylesheet">
	<link href="css/magnific-popup.css" rel="stylesheet">
	<link href="css/pop_up.css" rel="stylesheet"> -->
	
	<!-- YOUR CUSTOM CSS -->
	<!-- <link href="css/custom.css" rel="stylesheet"> -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='quickfood/css/custom.css') }}">

    
    <!-- Modernizr -->
	<!-- <script src="js/modernizr.js"></script>  -->
<script src="{{ url_for('static',filename='quickfood/js/modernizr.js') }}"></script>
<style>
	.the-icons {
	  font-size: 14px;
	  line-height: 28px;
	}
	.the-icons i{
	  font-size: 16px;
	}
	.codesOn .i-name {
	  display: none;
	}
	.codesOn .i-code {
	  display: inline;
	}
	.i-code {
	  display: none;
	  }
	</style>
    
</head>

<body>


    
    <!-- Header ================================================== -->
    <header class="sticky">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4 col-sm-4 col-4">
                <a href="index.html" id="logo">
                    <img src="/static/quickfood/img/logo.png" width="190" height="23" alt="" class="d-none d-sm-block">
                    <img src="/static/quickfood/img/logo_mobile.png" width="59" height="23" alt="" class="d-block d-sm-none">
                </a>
            </div>
            <nav class="col-md-8 col-sm-8 col-8">
            <a class="cmn-toggle-switch cmn-toggle-switch__htx open_close" href="javascript:void(0);"><span>Menu mobile</span></a>
            <div class="main-menu">
                <div id="header_menu">
                    <img src="/static/quickfood/img/logo.png" width="190" height="23" alt="">
                </div>
                <a href="#" class="open_close" id="close_in"><i class="icon_close"></i></a>
                <ul>
                    <li><a href="{{url_for('web.index')}}">Home</a></li>

                    <li class="submenu">
                    <a href="javascript:void(0);" class="show-submenu">Find<i class="icon-down-open-mini"></i></a>
                    <ul>
                        <li><a href="{{url_for('web.filter')}}">Restaurant</a></li>
                        <li><a href="{{url_for('web.foodfilter')}}">Food</a></li>
                    </ul>
                    </li>
                    
                    <li><a href="{{url_for('web.new_restaurant')}}">Add Restaurant</a></li>
                    <li class="submenu">
                    <a href="javascript:void(0);" class="show-submenu">Add Food<i class="icon-down-open-mini"></i></a>
                    <ul>
                        <li><a href="{{url_for('web.new_food')}}">Add with Form</a></li>
                        <li><a href="{{url_for('web.imageadd')}}">Add with Image</a></li>
                    </ul>
                    </li>
                    <li><a href="{{url_for('web.restaurants')}}">Restaurants</a></li>
                </ul>
            </div><!-- End main-menu -->
            </nav>
        </div><!-- End row -->
    </div><!-- End container -->
    </header>

    {% block content %}

    {% endblock %}

       <!-- Footer ================================================== -->
       <footer>
        <div class="container">
            <div class="row">
            
              
                <div class="col-md-6" id="newsletter">
                    <h3>Newsletter</h3>
                    <p>
                        Join our newsletter to keep be informed about offers and news.
                    </p>
                    <div id="message-newsletter_2">
                    </div>
                    <form method="post" action="assets/newsletter.php" name="newsletter_2" id="newsletter_2">
                        <div class="form-group">
                            <input name="email_newsletter_2" id="email_newsletter_2" type="email" value="" placeholder="Your mail" class="form-control">
                        </div>
                        <input type="submit" value="Subscribe" class="btn_1" id="submit-newsletter_2">
                    </form>
                </div>
             
            </div><!-- End row -->
         
        </div><!-- End container -->
    </footer>
    <!-- End Footer =============================================== -->

    <div class="layer"></div><!-- Mobile menu overlay mask -->

    <!-- Login modal -->

    
   
    
<!-- COMMON SCRIPTS -->
<script src="{{ url_for('static',filename='quickfood/js/jquery-3.7.0.min.js') }}"></script>
<script src="{{ url_for('static',filename='quickfood/js/common_scripts_min.js') }}"></script>
<script src="{{ url_for('static',filename='quickfood/js/functions.js') }}"></script>
<script src="{{ url_for('static',filename='quickfood/js/validate.js') }}"></script>

<!-- <script src="js/jquery-3.7.0.min.js"></script>
<script src="js/common_scripts_min.js"></script>
<script src="js/functions.js"></script>
<script src="assets/validate.js"></script> -->

<!-- SPECIFIC SCRIPTS -->


</body>
</html>

structure/templates/web/filter.html
{% extends "web/base.html" %}
{% block content %}
   

    <!-- Content ================================================== -->
    <div class="container margin_60_35">
        <div class="row">
            <div class="col-lg-4">
                <p>
                    <a class="btn_map" data-toggle="collapse" href="#collapseMap" aria-expanded="false" aria-controls="collapseMap" data-text-swap="Hide map" data-text-original="View on map">View on map</a>
                </p>
                <div class="box_style_2">
                    <h4 class="nomargin_top">Opening time <i class="icon_clock_alt float-right"></i></h4>
                    <ul class="opening_list">
                        <form method="post">
                            {{ form.csrf_token }}
                            {{ form.hidden_tag() }}
                            {{ form.restaurant_name.label }} {{ form.restaurant_name }}
                       
                            {{ form.submit }}
                          </form>
                    </ul>
                </div>
                <div class="box_style_2 d-none d-sm-block" id="help">
                    <i class="icon_lifesaver"></i>
                    <h4>Need <span>Help?</span></h4>
                    <a href="tel://004542344599" class="phone">+45 423 445 99</a>
                    <small>Monday to Friday 9.00am - 7.30pm</small>
                </div>
            </div>
            <div class="col-lg-8">
        
                <div id="tools">
                    <div class="row">
                        <div class="col-md-3 col-sm-4 col-5">
                            <div class="styled-select">
                                <select name="sort_rating" id="sort_rating">
                                    <option value="" selected="">Sort by price</option>
                                    <option value="lower">Lowest price</option>
                                    <option value="higher">Highest price</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-9 col-sm-8 col-7">
                            <a href="grid_list.html" class="bt_filters"><i class="icon-th"></i></a>
                        </div>
                    </div>
                </div><!--End tools -->
                {% if  restaurants %}
                {%for restaurant in restaurants %}
                <div class="strip_list wow fadeIn" data-wow-delay="0.1s">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="desc">
                                <div class="thumb_strip">
                                    <a href="{{url_for('web.restaurant',id=restaurant.id)}}"><img src="/static/quickdood/img/thumb_food.jpg" alt=""></a>
                                </div>
                                <div class="rating">
                                    <i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star "></i><i class="icon_star"></i> (<small><a href="#0">98 reviews</a></small>)
                                </div>
                                <h3>{{restaurant.name}} - </h3>
                            
                                <div class="location">
                                   {{restaurant.location}}  
                                </div>
                                <ul>
                                    <li>Take away<i class="icon_check_alt2 ok"></i></li>
                                    <li>Delivery<i class="icon_check_alt2 no"></i></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="go_to">
                                <div>
                                    <a href="{{url_for('web.restaurant',id=restaurant.id)}}" class="btn_1">View Menu</a>
                                </div>
                        </div>
                        </div>
                    </div>
                    </div><!-- End row-->
\                {%endfor%}
{%else%}
           

        <a href="#0" class="load_more_bt wow fadeIn" data-wow-delay="0.2s">No Results Fpund</a>  
        {%endif%}
</div><!-- End col-md-9-->
        </div><!-- End row -->
    </div><!-- End container -->
</div><!-- End container -->
    <!-- End Content =============================================== -->
{%endblock%}

structure/templates/web/index.html
{% extends "web/base.html" %}
{% block content %}
    
    <!-- SubHeader =============================================== -->
    <section class="parallax-window" id="home" data-parallax="scroll" data-image-src="/static/quickfood/img/sub_header_home.jpg" data-natural-width="1400" data-natural-height="550">
        <div id="subheader">
            <div id="sub_content">
                <h1>Restaurants Directory</h1>
                <p>
                    Search for restaurants.
                </p>
                <form method="post" action="/search">
                    <div id="custom-search-input">
                        <div class="input-group ">
                            <span class="input-group-btn">
                            <input type="text" name="text" class=" search-query" placeholder="Enter Name">
                                    <select class="" name="type">
                                        <option value="restaurant"><span>Restaurant</i> </span></option>
                                        <option value="food"><span>Food</i> </span></option>
                                    </select>
                                    </span>
                            <span class="input-group-btn">
                                
                            <input type="submit" class="btn_search" value="">
                            </span>
                        </div>
                    </div>
                </form>
            </div><!-- End sub_content -->
        </div><!-- End subheader -->
        </section><!-- End section -->
    <!-- End SubHeader ============================================ -->

    <div class="white_bg">
        <div class="container margin_60">
            <div class="main_title">
                <h2 class="nomargin_top">RESTAURANTS</h2>
                <p>
                    Browse through restaurants for their menu.
                </p>
            </div>
            <div class="row">
                {% for restaurant in restaurants.items %}
                <div class="col-lg-6">
                    
                    <a href="{{url_for('web.restaurant',id=restaurant.id)}}" class="strip_list">
                        <div class="desc">
                            <div class="thumb_strip">
                                <img src="/static/quickfood/img/thumb_restaurant.jpg" alt="">
                            </div>
                            <div class="rating">
                                <i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star voted"></i><i class="icon_star"></i>
                            </div>
                            <h3>{{restaurant.name}}</h3>
                           
                            <div class="location">
                                {{restaurant.location}} 
                            </div>
                            <ul>
                                <li>Delivery available<i class="icon_check_alt2 ok"></i></li>
                            </ul>
                        </div><!-- End desc-->
                    </a><!-- End strip_list-->
                    </div>
                    {%endfor%}
                  
             
            </div><!-- End row -->
        </div><!-- End container -->
        <!-- Pagination links -->
<div class="pagination">
    <span>Page {{ restaurants.page }} of {{ restaurants.pages }}.</span>
    {% if restaurants.has_prev %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ restaurants.prev_num }}">previous</a>
    {% endif %}
    {% if restaurants.has_next %}
        <a href="?page={{ restaurants.next_num }}">next</a>
        <a href="?page={{ restaurants.pages }}">last &raquo;</a>
    {% endif %}
</div>
    </div><!-- End white_bg -->
    <div class="high_light">
        <div class="container">
            <h3>Choose from over 100 Restaurants</h3>
            <p>100 + Menus to choose from.</p>
            <a href="list_page.html">View all Restaurants</a>
        </div><!-- End container -->
    </div><!-- End hight_light -->
   
    </div><!-- End container -->
    
{% endblock %}