structure/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField,SelectField ,IntegerField,TextAreaField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from flask_wtf.file import FileField,FileAllowed

from flask_login import current_user
from structure.models import User

class LoginForm(FlaskForm):
    email = StringField('Email',validators=[DataRequired(),Email()])
    password = PasswordField('Password',validators=[DataRequired()])
    submit = SubmitField('Log In')

class RegistrationForm(FlaskForm):
    email = StringField('Email',validators=[DataRequired(),Email()])
    username = StringField('UserName',validators=[DataRequired()])
    name = StringField('Name',validators=[DataRequired()])
    last_name = StringField('Last Name')
    number = StringField('Number',validators=[DataRequired()])
    role = SelectField('Sign Up as a:',validators=[DataRequired()],choices=[('user', 'user'), ('vendor','vendor')])
    password = PasswordField('Password',validators=[DataRequired(),EqualTo('pass_confirm',message='Passwords must match!')])
    pass_confirm = PasswordField('Confirm Password',validators=[DataRequired()])
    channels = StringField('Text')
    ip = StringField('IP')
    create_extension = SelectField('Inbound',validators=[DataRequired()],choices=[('yes', 'Yes'), ('no', 'No')])
    other = TextAreaField('Text')
    codecs = StringField('Codecs')
    status = SelectField('Status',validators=[DataRequired()],choices=[('verified', 'Verified'), ('unverified', 'Unverified')])
    certificate = FileField('Certificate', validators=[ FileAllowed(['jpg','png','gif','jpeg'])])
    inbound = SelectField('Inbound',validators=[DataRequired()],choices=[('yes', 'Yes'), ('no', 'No')])
    outbound = SelectField('Outbound',validators=[DataRequired()],choices=[('yes', 'Yes'), ('no', 'No')])
    provider = SelectField('Provider',validators=[DataRequired()],choices=[('mtn', 'MTN'), ('vodafone', 'Vodafone')])
    ratecard = SelectField('Provider',validators=[DataRequired()],choices=[('MTN O.15 Termination', 'MRH1-zAeN'), ('Vodafone 0.16 Termination', '7M8u-2Pv'),('MTN International','mB_2-ijp6'),('Vezeti','ytV2-Kjbn')])

    
    submit = SubmitField('Sign Up!')

    def check_email(self,field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already!')

    def check_username(self,field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Your username has been registered already!')


class UpdateUserForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(),Email()])
    username = StringField('Username', validators=[DataRequired()])
    name = StringField('Name', validators=[DataRequired()])
    artist = StringField('Artist', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    plan = StringField('Plan', validators=[DataRequired()])
    number = StringField('Number', validators=[DataRequired()])
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png'])])
    location = StringField('Location', validators=[DataRequired()])
    pref_help = StringField('What are you seeking help for?')
    pref_medium = StringField('What is your preferred medium for the session? eg whatsapp, zoom etc')
    pref_gender = StringField('Do you have a preferred gender for the session?')
    submit = SubmitField('Update Details!')

    def check_email(self, field):
        # Check if not None for that user email!
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already!')

    def check_username(self, field):
        # Check if not None for that username!
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Sorry, that username is taken!')




class UpdateAgentForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(),Email()])
    username = StringField('Username', validators=[DataRequired()])
    name = StringField('Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    plan = StringField('Plan', validators=[DataRequired()])
    number = StringField('Number', validators=[DataRequired()])
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png'])])
    location = StringField('Location', validators=[DataRequired()])
    pref_help = StringField('What are you seeking help for?')
    pref_medium = StringField('What is your preferred medium for the session? eg whatsapp, zoom etc')
    pref_gender = StringField('Do you have a preferred gender for the session?')
    specialty = StringField('What is your specialty?')
    biography = TextAreaField('Biography')
    experience = StringField('Years of experience.')
    baseprice = IntegerField('Base Price')
    platform = StringField('What platforms can you have have your sessions? Eg zoom, In Person')
    submit = SubmitField('Update Details!')

    def check_email(self, field):
        # Check if not None for that user email!
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already!')

    def check_username(self, field):
        # Check if not None for that username!
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Sorry, that username is taken!')

structure/users/views.py
# users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint,session
from flask_login import login_user, current_user, logout_user, login_required
from structure import db,photos,mail 
from structure.models import User 
from structure.users.forms import RegistrationForm,LoginForm,UpdateUserForm
from structure.users.picture_handler import add_profile_pic
import secrets
import requests
import os
from requests.auth import HTTPBasicAuth
from flask_mail import Mail, Message
# from structure.core.views import generate_secure_password
import random
import string

users = Blueprint('users',__name__)


def generate_secure_password(length=12):
    alphabet = string.ascii_letters + string.digits + string.punctuation
    secure_password = ''.join(secrets.choice(alphabet) for _ in range(length))
    return secure_password


connex_username = os.environ.get('connex_username')
connex_password = os.environ.get('connex_password')
# register
@users.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()
    print("hghgj")
    # if form.validate_on_submit():
    if request.method == 'POST':
        print("df")
        user = User(email=form.email.data,
                    name=form.name.data,
                    username=form.username.data,
                    password=form.password.data,
                    last_name=form.last_name.data,role="user",
                    number=form.number.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering!')
        if user.role == 'user':
            session['id'] = user.id
            return redirect(url_for('users.enterartist'))
        else:
            return redirect(url_for('users.vendorregister',id=user.id))
            

    return render_template('user/signup.html',form=form)













@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        # Grab the user from our User Models table
        user = User.query.filter_by(email=form.email.data).first()
        
        
        userr = User.query.filter_by(email=form.email.data).first()
        


        if user is not None and user.check_password(form.password.data)  :
            #Log in the user
            session['name'] = userr.name
            session['role'] = userr.role
            session['email'] = form.email.data
            session['id'] = user.id
            print("session")
            print(session['name'])
            login_user(user)
            flash('Logged in successfully.')




            # If a user was trying to visit a page that requires a login
            # flask saves that URL as 'next'.
            next = request.args.get('next')

            # So let's now check if that next exists, otherwise we'll go to
            # the welcome page.
            if next == None or not next[0]=='/':
                next = url_for('core.agent_dashboard')
            

            return redirect(next)
        else:
            session['loginmsg'] = "Invalid credentials. Try again"
            next = request.args.get('next')

            # So let's now check if that next exists, otherwise we'll go to
            # the welcome page.
            if next == None or not next[0]=='/':
                next = url_for('core.dashboard')
            

            return redirect(next)




    return render_template('user/signin.html', form=form)

# logout
@users.route("/logout")
def logout():
    logout_user()
    session.pop('email',None)
    session.pop('name',None)
    session.pop('role',None)
    # session.pop('loginmsg',None)

    return redirect(url_for("users.login"))


# account (update UserForm)
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    userinfo = User.query.filter_by(email=session["email"]).first_or_404()

    form = UpdateUserForm()

    if request.method == 'POST':

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.name = form.name.data
        current_user.number = form.number.data
        current_user.location = form.location.data
        current_user.pref_help = form.pref_help.data
        current_user.pref_therapistgender = form.pref_gender.data
        current_user.pref_medium = form.pref_medium.data
        

        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('userportal.uprofile'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('userportal/profile.html', profile_image=profile_image, form=form,userinfo=userinfo)




# account (update UserForm)
@users.route("/auth/artist", methods=['GET', 'POST'])
# @login_required
def enterartist():
    # userinfo = User.query.filter_by(id=session["id"]).first_or_404()

    form = UpdateUserForm()

    if request.method == 'POST':
        artist_mbid = "6f937dd2-1aa8-49ce-9052-8127714db3d2"

        # Define the MusicBrainz API endpoint for artist lookup
        print(form.artist.data)
        base_url = "https://musicbrainz.org/ws/2/artist"
        artist_name= form.artist.data
        # Define the parameters for the search
        params = {
            "fmt": "json",  # Return results in JSON format
            "query": f"{artist_name}",  # Search for the artist with the specified MBID
            # "inc": "releases"  # Include releases (songs) by the artist in the response
        }

        # Make the API request
        response = requests.get(base_url, params=params)
        print(response)

        # Check if the request was successful
        if response.status_code == 200:
            # Parse the JSON response
            artist_data = response.json()
            print('artist_data')
            # print(artist_data)

            # Extract the list of releases (songs) by the artist
            artists = artist_data.get('artists', [])
            print(artists)

            # # Print the titles of the songs
            # for work in releases:
            #     title = work.get('title')
            #     print(f"Song Title: {title}")
            return render_template('user/enterartist.html',form=form,artists=artists)
        else:
            print(f"Error: {response.status_code} - {response.text}")
        print("done")
        # if form.picture.data:
        
        

 
   
    return render_template('user/enterartist.html',form=form)



@users.route('/selectartist/<mbid>', methods=['POST','GET'])
def selectartist(mbid):
    if request.method == 'POST':
        # Get the user's input MBID from the form (assuming it's in a field named 'mbid' in a form)
        user_mbid = request.form.get('mbid')

        # Update the user's MBID in the database
    user = User.query.filter_by(id=session["id"]).first_or_404()
    if user:
        user.mbid = mbid
        db.session.commit()

    return redirect(url_for('core.dashboard'))

# # account (update UserForm)
# @users.route("/auth/artistsongs", methods=['GET', 'POST'])
# # @login_required
# def choosesongs():
#     # userinfo = User.query.filter_by(email=session["email"]).first_or_404()

#     form = UpdateUserForm()

#     if request.method == 'POST':
#         artist_mbid = "6f937dd2-1aa8-49ce-9052-8127714db3d2"

#         # Define the MusicBrainz API endpoint for artist lookup
#         base_url = "https://musicbrainz.org/ws/2/artist"

#         # Define the parameters for the search
#         params = {
#             "fmt": "json",  # Return results in JSON format
#             "query": f"arid:{artist_mbid}",  # Search for the artist with the specified MBID
#             # "inc": "releases"  # Include releases (songs) by the artist in the response
#         }

#         # Make the API request
#         response = requests.get(base_url, params=params)
#         print(response)

#         # Check if the request was successful
#         if response.status_code == 200:
#             # Parse the JSON response
#             artist_data = response.json()
#             print('artist_data')
#             print(artist_data)

#             # Extract the list of releases (songs) by the artist
#             releases = artist_data.get('releases', [])
#             print(releases)

#             # Print the titles of the songs
#             for work in releases:
#                 title = work.get('title')
#                 print(f"Song Title: {title}")

#         else:
#             print(f"Error: {response.status_code} - {response.text}")
#         print("done")
#         # if form.picture.data:
        
        

 
   
#     return render_template('user/enterartist.html',form=form)










# user's list of Blog posts

structure/templates/user/auth-confirm-mail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Confirm Email | Adminto - Responsive Admin Dashboard Template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Coderthemes" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="assets/images/favicon.ico">

		<!-- App css -->

		<link href="assets/css/app.min.css" rel="stylesheet" type="text/css" id="app-style" />

		<!-- icons -->
		<link href="assets/css/icons.min.css" rel="stylesheet" type="text/css" />

    </head>

    <body class="loading authentication-bg authentication-bg-pattern">

        <div class="account-pages mt-5 mb-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-8 col-lg-6 col-xl-4">
                        <div class="text-center">
                            <a href="index.html">
                                <img src="assets/images/logo-dark.png" alt="" height="22" class="mx-auto">
                            </a>
                            <p class="text-muted mt-2 mb-4">Responsive Admin Dashboard</p>
                        </div>
                        <div class="card text-center">

                            <div class="card-body p-4">
                                
                                <div class="mb-4">
                                    <h4 class="text-uppercase mt-0">Confirm Email</h4>
                                </div>
                                <img src="assets/images/mail_confirm.png" alt="img" width="86" class="mx-auto d-block" />

                                <p class="text-muted font-14 mt-2"> A email has been send to <b>youremail@domain.com</b>.
                                    Please check for an email from company and click on the included link to
                                    reset your password. </p>

                                <a href="index.html" class="btn d-block btn-pink waves-effect waves-light mt-3">Back to Home</a>

                            </div> <!-- end card-body -->
                        </div>
                        <!-- end card -->

                    </div> <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end page -->

        <!-- Vendor -->
        <script src="assets/libs/jquery/jquery.min.js"></script>
        <script src="assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="assets/libs/simplebar/simplebar.min.js"></script>
        <script src="assets/libs/node-waves/waves.min.js"></script>
        <script src="assets/libs/waypoints/lib/jquery.waypoints.min.js"></script>
        <script src="assets/libs/jquery.counterup/jquery.counterup.min.js"></script>
        <script src="assets/libs/feather-icons/feather.min.js"></script>

        <!-- App js -->
        <script src="assets/js/app.min.js"></script>
        
    </body>
</html>

structure/templates/user/enterartist.html
<!DOCTYPE html>
<html lang="en" class="no-js">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TRS</title>
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="Themesdesign" />

    <link rel="shortcut icon" href="images/favicon.ico">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" type="text/css"
    href="{{ url_for('static',filename='auth/layouts/css/bootstrap.min.css') }}">
    <!--Material Icon -->
    <link rel="stylesheet" type="text/css" href="css/materialdesignicons.min.css" />
    <link rel="stylesheet" type="text/css"
    href="{{ url_for('static',filename='auth/layouts/css/materialdesignicons.min.css') }}">
    <!-- Custom  Css -->
    <link rel="stylesheet" type="text/css" href="css/style.css" />
    <link rel="stylesheet" type="text/css"
    href="{{ url_for('static',filename='auth/layouts/css/style.css') }}">

</head>

<body>

    <!-- START Auth -->
    <section class="authentication-box vh-100">
        <div class="bg-overlay"></div>
        <div class="container-fluid p-0">
            <div class="row g-0 align-items-center">
                <div class="col-lg-3">
                    <div class="bg-white vh-100">
                        <div class="row g-0 justify-content-center d-flex vh-100 align-items-center">
                            <div class="col-lg-11">
                               <div class="authen-box" style="width: 700px;">
                                <div class="text-center pb-4 mb-2">
                                    <img src="images/logo-dark.png" alt="" height="24">
                                </div>
                                <div class="auth-contents">
                                    <div class="text-center">
                                        <h4 class="fw-normal">Enter artist name<span class="fw-bold"></span></h4>
                                        <p class="text-muted">Find artist.</p>
                                    </div>
                                    <form method="post" class="custom-form mt-4 pt-2">
                                        <div class="mb-3">
                                            <label class="form-label fw-bold f-15">Artist Name</label>
                                            <input type="text" class="form-control" id="artist" name="artist"
                                                placeholder="Enter artist name">
                                        </div>
                                      
                                       
                                        <div class="text-center mt-3">
                                            <button class="btn btn-success shadow-none w-100 rounded-pill" type="submit">Search</button>
                                        </div>
                                        <hr>
                                        <div class="mt-3 text-center">
                                            {%if artists%}
                                            {%for artist in artists%}
                                            <ul>
                                                <li><a href="{{url_for('users.selectartist',mbid=artist.id)}}">{{artist.name}}</a></li>
                                            </ul>
                                            {%endfor%}
                                            {%endif%}
                                        </div>
                                    </form>
                                    <!-- end form -->
                                </div>
                               </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end -->
                <div class="col-lg-9" style="left: 250px;">
                    <div class="row g-0 justify-content-center  auth-carousel">
                        <div class="col-lg-7">
                            <div class="d-none d-lg-inline-block">
                                <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                                    <div class="carousel-indicators">
                                        <button type="button" data-bs-target="#carouselExampleIndicators"
                                            data-bs-slide-to="0" class="active" aria-current="true"
                                            aria-label="Slide 1"></button>
                                        <button type="button" data-bs-target="#carouselExampleIndicators"
                                            data-bs-slide-to="1" aria-label="Slide 2"></button>
                                        <button type="button" data-bs-target="#carouselExampleIndicators"
                                            data-bs-slide-to="2" aria-label="Slide 3"></button>
                                    </div>
                                    <div class="carousel-inner">
                                        <div class="carousel-item active">
                                            <div class="testi-contain text-white">
                                                
                                                <p class="mt-4 pt-2 lh-lg f-20">“Really nice idea, this adds a little flavor to all those dummy-texts! I can recommend 
                                                    setting up keystrokes for this, it'll speed up the process a lot  malesuada nibh diam on tortor neaded to throw curve balls.”</p>
                                                    <div class="d-flex mt-4 align-items-center">
                                                        <div class="testi-img">
                                                            <img src="images/users/avatar-1.jpg"
                                                                class="me-3 img-fluid avatar-md img-thumbnail rounded-circle" alt="...">
                                                        </div>
                                                        <div class="flex-1 ms-2">
                                                            <h5 class="mt-0 mb-0 f-19">Michael E. Johnson</h5>
                                                            <p class="mb-0 f-15"><i class="mdi mdi-circle text-success f-12 me-2"></i>Web
                                                                Designer</p>
                                                        </div>
                                                    </div>
                                            </div>
                                        </div>
                                        <!-- end -->
                                        <div class="carousel-item">
                                            <div class="testi-contain text-white">
                                                
                                                <p class="mt-4 pt-2 lh-lg f-20">“Our task must be to free
                                                    ourselves by widening our circle of compassion to embrace all living
                                                    creatures and the whole of quis consectetur nunc sit amet semper justo.
                                                    nature and its beauty.”</p>
                                                <div class="d-flex mt-4 align-items-center">
                                                    <div class="testi-img">
                                                        <img src="images/users/avatar-2.jpg"
                                                            class="me-3 img-fluid avatar-md img-thumbnail rounded-circle" alt="...">
                                                    </div>
                                                    <div class="flex-1 ms-2">
                                                        <h5 class="mt-0 mb-0 f-19">William M. Hamilton</h5>
                                                        <p class="mb-0 f-15"><i class="mdi mdi-circle text-success f-12 me-2"></i>Web
                                                            Developer</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end -->
                                        <div class="carousel-item">
                                            <div class="testi-contain text-white">
                                                <p class="mt-4 pt-2 lh-lg f-20">“I've learned that people will
                                                    forget what you said, people will forget what you did, but people will
                                                    never forget how donec in efficitur lectus, nec lobortis metus you made
                                                    them feel.”</p>
                                                <div class="d-flex mt-4 align-items-center">
                                                    <div class="testi-img">
                                                        <img src="images/users/avatar-3.jpg"
                                                            class="me-3 avatar-md img-fluid img-thumbnail rounded-circle" alt="...">
                                                    </div>
                                                    <div class="flex-1 ms-2">
                                                        <h5 class="mt-0 mb-0 f-19">Stephen R. Hunter</h5>
                                                        <p class="mb-0 f-15"><i class="mdi mdi-circle text-success f-12 me-2"></i>React
                                                            Developer</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end -->
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- end col -->
                    </div>
                </div>
                <!-- end col -->
            </div>
        </div>
    </section>
    <!-- END Auth -->

    <!-- bootstrap -->
    <script src="js/bootstrap.bundle.min.js"></script>
    <script src="{{ url_for('static',filename='auth/layouts/js/bootstrap.bundle.min.js') }}"></script>

    <!-- CUSTOM JS -->
    <script src="js/app.js"></script>
    <script src="{{ url_for('static',filename='auth/layouts/js/app.js') }}"></script>

</body>

</html>

structure/templates/user/login.html
{% extends "user/base.html" %}
{% block content %}
                        <div class="card">
                            <div class="card-body p-4">
                                
                                <div class="text-center mb-4">
                                    <h4 class="text-uppercase mt-0">Sign In</h4>
                                </div>

                                <form action="#">
                                    <div class="mb-3">
                                        <label for="emailaddress" class="form-label">Email address</label>
                                        <input class="form-control" type="email" id="emailaddress" required="" placeholder="Enter your email">
                                    </div>

                                    <div class="mb-3">
                                        <label for="password" class="form-label">Password</label>
                                        <input class="form-control" type="password" required="" id="password" placeholder="Enter your password">
                                    </div>

                                    <div class="mb-3">
                                        <div class="form-check">
                                            <input type="checkbox" class="form-check-input" id="checkbox-signin" checked>
                                            <label class="form-check-label" for="checkbox-signin">Remember me</label>
                                        </div>
                                    </div>

                                    <div class="mb-3 d-grid text-center">
                                        <button class="btn btn-primary" type="submit"> Log In </button>
                                    </div>
                                </form>

                            </div> <!-- end card-body -->
                        </div>
                        <!-- end card -->

                        <div class="row mt-3">
                            <div class="col-12 text-center">
                                <p> <a href="pages-recoverpw.html" class="text-muted ms-1"><i class="fa fa-lock me-1"></i>Forgot your password?</a></p>
                                <p class="text-muted">Don't have an account? <a href="pages-register.html" class="text-dark ms-1"><b>Sign Up</b></a></p>
                            </div> <!-- end col -->
                        </div>
                        <!-- end row -->

                    </div> <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        {%endblock%}