structure/users/views.py
# users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint,session
from flask_login import login_user, current_user, logout_user, login_required
from structure import db,photos,mail 
from structure.models import User 
from structure.users.forms import RegistrationForm,LoginForm,UpdateUserForm
from structure.users.picture_handler import add_profile_pic
import secrets
import requests
import os
from requests.auth import HTTPBasicAuth
from flask_mail import Mail, Message
# from structure.core.views import generate_secure_password
import random
import string

users = Blueprint('users',__name__)


def generate_secure_password(length=12):
    alphabet = string.ascii_letters + string.digits + string.punctuation
    secure_password = ''.join(secrets.choice(alphabet) for _ in range(length))
    return secure_password


connex_username = os.environ.get('connex_username')
connex_password = os.environ.get('connex_password')
# register
@users.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()
    print("hghgj")
    # if form.validate_on_submit():
    if request.method == 'POST':
        print("df")
        user = User(email=form.email.data,
                    name=form.name.data,
                    username=form.username.data,
                    password=form.password.data,
                    last_name=form.last_name.data,role="user",
                    number=form.number.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering!')
        if user.role == 'user':
            session['id'] = user.id
            return redirect(url_for('users.enterartist'))
        else:
            return redirect(url_for('users.vendorregister',id=user.id))
            

    return render_template('user/signup.html',form=form)













@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        # Grab the user from our User Models table
        user = User.query.filter_by(email=form.email.data).first()
        
        
        userr = User.query.filter_by(email=form.email.data).first()
        


        if user is not None and user.check_password(form.password.data)  :
            #Log in the user
            session['name'] = userr.name
            session['role'] = userr.role
            session['email'] = form.email.data
            session['id'] = user.id
            print("session")
            print(session['name'])
            login_user(user)
            flash('Logged in successfully.')




            # If a user was trying to visit a page that requires a login
            # flask saves that URL as 'next'.
            next = request.args.get('next')

            # So let's now check if that next exists, otherwise we'll go to
            # the welcome page.
            if next == None or not next[0]=='/':
                next = url_for('core.agent_dashboard')
            

            return redirect(next)
        else:
            session['loginmsg'] = "Invalid credentials. Try again"
            next = request.args.get('next')

            # So let's now check if that next exists, otherwise we'll go to
            # the welcome page.
            if next == None or not next[0]=='/':
                next = url_for('core.dashboard')
            

            return redirect(next)




    return render_template('user/signin.html', form=form)

# logout
@users.route("/logout")
def logout():
    logout_user()
    session.pop('email',None)
    session.pop('name',None)
    session.pop('role',None)
    # session.pop('loginmsg',None)

    return redirect(url_for("users.login"))


# account (update UserForm)
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    userinfo = User.query.filter_by(email=session["email"]).first_or_404()

    form = UpdateUserForm()

    if request.method == 'POST':

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.name = form.name.data
        current_user.number = form.number.data
        current_user.location = form.location.data
        current_user.pref_help = form.pref_help.data
        current_user.pref_therapistgender = form.pref_gender.data
        current_user.pref_medium = form.pref_medium.data
        

        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('userportal.uprofile'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('userportal/profile.html', profile_image=profile_image, form=form,userinfo=userinfo)




# account (update UserForm)
@users.route("/auth/artist", methods=['GET', 'POST'])
# @login_required
def enterartist():
    # userinfo = User.query.filter_by(id=session["id"]).first_or_404()

    form = UpdateUserForm()

    if request.method == 'POST':
        artist_mbid = "6f937dd2-1aa8-49ce-9052-8127714db3d2"

        # Define the MusicBrainz API endpoint for artist lookup
        print(form.artist.data)
        base_url = "https://musicbrainz.org/ws/2/artist"
        artist_name= form.artist.data
        # Define the parameters for the search
        params = {
            "fmt": "json",  # Return results in JSON format
            "query": f"{artist_name}",  # Search for the artist with the specified MBID
            # "inc": "releases"  # Include releases (songs) by the artist in the response
        }

        # Make the API request
        response = requests.get(base_url, params=params)
        print(response)

        # Check if the request was successful
        if response.status_code == 200:
            # Parse the JSON response
            artist_data = response.json()
            print('artist_data')
            # print(artist_data)

            # Extract the list of releases (songs) by the artist
            artists = artist_data.get('artists', [])
            print(artists)

            # # Print the titles of the songs
            # for work in releases:
            #     title = work.get('title')
            #     print(f"Song Title: {title}")
            return render_template('user/enterartist.html',form=form,artists=artists)
        else:
            print(f"Error: {response.status_code} - {response.text}")
        print("done")
        # if form.picture.data:
        
        

 
   
    return render_template('user/enterartist.html',form=form)



@users.route('/selectartist/<mbid>', methods=['POST','GET'])
def selectartist(mbid):
    if request.method == 'POST':
        # Get the user's input MBID from the form (assuming it's in a field named 'mbid' in a form)
        user_mbid = request.form.get('mbid')

        # Update the user's MBID in the database
    user = User.query.filter_by(id=session["id"]).first_or_404()
    if user:
        user.mbid = mbid
        db.session.commit()

    return redirect(url_for('core.dashboard'))

# # account (update UserForm)
# @users.route("/auth/artistsongs", methods=['GET', 'POST'])
# # @login_required
# def choosesongs():
#     # userinfo = User.query.filter_by(email=session["email"]).first_or_404()

#     form = UpdateUserForm()

#     if request.method == 'POST':
#         artist_mbid = "6f937dd2-1aa8-49ce-9052-8127714db3d2"

#         # Define the MusicBrainz API endpoint for artist lookup
#         base_url = "https://musicbrainz.org/ws/2/artist"

#         # Define the parameters for the search
#         params = {
#             "fmt": "json",  # Return results in JSON format
#             "query": f"arid:{artist_mbid}",  # Search for the artist with the specified MBID
#             # "inc": "releases"  # Include releases (songs) by the artist in the response
#         }

#         # Make the API request
#         response = requests.get(base_url, params=params)
#         print(response)

#         # Check if the request was successful
#         if response.status_code == 200:
#             # Parse the JSON response
#             artist_data = response.json()
#             print('artist_data')
#             print(artist_data)

#             # Extract the list of releases (songs) by the artist
#             releases = artist_data.get('releases', [])
#             print(releases)

#             # Print the titles of the songs
#             for work in releases:
#                 title = work.get('title')
#                 print(f"Song Title: {title}")

#         else:
#             print(f"Error: {response.status_code} - {response.text}")
#         print("done")
#         # if form.picture.data:
        
        

 
   
#     return render_template('user/enterartist.html',form=form)










# user's list of Blog posts

structure/templates/mainnav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>BRAN</title>

    <!-- Primary Meta Tags -->
    <meta name="title" content="Play - Free Open Source HTML Bootstrap Template by UIdeck">
    <meta name="description" content="Play - Free Open Source HTML Bootstrap Template by UIdeck Team">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <!--<meta property="og:url" content="https://uideck.com/play/">-->
    <meta property="og:title" content="Airrand">
    <meta property="og:description" content="Airrand">
    <!--<meta property="og:image" content="https://uideck.com/wp-content/uploads/2021/09/play-meta-bs.jpg">-->

    <!-- Twitter
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="https://uideck.com/play/">
    <meta property="twitter:title" content="Play - Free Open Source HTML Bootstrap Template by UIdeck">
    <meta property="twitter:description" content="Play - Free Open Source HTML Bootstrap Template by UIdeck Team">
    <meta property="twitter:image" content="https://uideck.com/wp-content/uploads/2021/09/play-meta-bs.jpg">
    -->
    <!--====== Favicon Icon ======-->
    <!-- <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='images/favicon.ico') }}"> -->


    <!-- ===== All CSS files ===== -->
    <link href="https://maxcdn.icons8.com/fonts/line-awesome/1.1/css/line-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/animate.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/lineicons.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/ud-styles.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css2/homepage.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css2/pricing-page.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css2/payment-details-drop-down.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css2/dashboard.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='oldmango/fonts/icomoon/style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='oldmango/css/owl.carousel.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='oldmango/css/bootstrap.min.css') }}">

</head>
<body>
<!-- ====== Header Start ====== -->

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#" style="color: #e72b34;"> BRAN </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse " style="margin-left: 70%;" id="navbarSupportedContent">
  
        <div class="form-inline my-2 my-lg-0 ">
          <a class="nav-link" href="" id="navbarDropdown" role="button" >
            Home
          </a>  
          {% if current_user.is_authenticated %}
                      <a class="nav-link" href="{{ url_for('users.logout') }}" id="navbarDropdown" role="button" >
            Logout
          </a>        
          {% else %}
          <a class="nav-link" href="{{ url_for('users.login') }}" id="navbarDropdown" role="button" >
            Login
          </a>   
     
          {% endif %}
    
         </div>
      </div>
</nav>

{% block content %}

{% endblock %}
</div>
</div>
</div>


<!-- Footer -->
<footer class=" text-white" style="background-color:#282828;margin-top: auto;">
    <!-- Grid container -->

    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2023 Copyright:
        <a class="text-white" href="">TSL</a>
    </div>
    <!-- Copyright -->
</footer>
<!-- Footer -->
</section>


<!-- ====== All Javascript Files ====== -->
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='js/bootstrap.bundle.min.js') }}">

<script src="{{ url_for('static',filename='js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/wow.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/main.js') }}"></script>
<script src="assets/js/bootstrap.bundle.min.js"></script>

<script src="assets/js/wow.min.js"></script>
<script src="assets/js/main.js"></script>
<script>
    // ==== for menu scroll
    const pageLink = document.querySelectorAll(".ud-menu-scroll");

    pageLink.forEach((elem) => {
        elem.addEventListener("click", (e) => {
            e.preventDefault();
            document.querySelector(elem.getAttribute("href")).scrollIntoView({
                behavior: "smooth",
                offsetTop: 1 - 60,
            });
        });
    });

    // section menu active
    function onScroll(event) {
        const sections = document.querySelectorAll(".ud-menu-scroll");
        const scrollPos =
            window.pageYOffset ||
            document.documentElement.scrollTop ||
            document.body.scrollTop;

        for (let i = 0; i < sections.length; i++) {
            const currLink = sections[i];
            const val = currLink.getAttribute("href");
            const refElement = document.querySelector(val);
            const scrollTopMinus = scrollPos + 73;
            if (
                refElement.offsetTop <= scrollTopMinus &&
                refElement.offsetTop + refElement.offsetHeight > scrollTopMinus
            ) {
                document
                    .querySelector(".ud-menu-scroll")
                    .classList.remove("active");
                currLink.classList.add("active");
            } else {
                currLink.classList.remove("active");
            }
        }
    }

    window.document.addEventListener("scroll", onScroll);


</script>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<!-- <script src="https://checkout.flutterwave.com/v3.js"></script> -->

</body>
</html>

structure/templates/menu.html
{% extends "mainnav.html" %}
{% block content %}  

<form method="post" enctype="multipart/form-data" >
 
   
        <div class="md:flex items-center gap-10">
            <label class="md:w-32 text-right"> File </label>
            <div class="flex-1 max-md:mt-4">
                <input type="file" name ="images"  class="lg:w-1/2 w-full" multiple>
            </div>
        </div>
        
    
    </div>

    <div class="flex items-center gap-4 mt-16 lg:pl-[10.5rem]">
        <button type="submit" class="button lg:px-10 bg-primary text-white max-md:flex-1"> Save <span class="ripple-overlay"></span></button>
    </div>
</form>


{%for item in menu_items %}
{{item}}
{%endfor%}

{%endblock%}

structure/templates/register.html
{% extends "mainnav.html" %}
{% block content %}
   
        
       
          <div class="container" style="margin-top: -50px;margin-bottom: 200px;">

      
            <div class="row justify-content-center">
              <div class="col-md-10">
                
                <div class="row align-items-center">
                  <div class="col-lg-7 mb-5 mb-lg-0" style="margin-top: 250px;">
      
                    <h2 class="mb-5">Sign Up <br> </h2>
      
                    <form class="border-right pr-5 mb-5" method="post" id="contactForm" name="contactForm" method="post" >
                        {{form.hidden_tag()}}
                      
                        <div class="row">
                          <div class="col-md-12 form-group">
                            {{form.name.label()}}{{form.name(class="form-control")}}
                          </div>
                        </div> <div class="row">
                          <div class="col-md-12 form-group">
                            {{form.email.label()}}{{form.email(class="form-control")}}
                          </div>
                        </div> <div class="row">
                          <div class="col-md-12 form-group">
                            {{form.username.label()}}{{form.username(class="form-control")}}
                          </div>
                        </div> 
                         <div class="row">
                          <div class="col-md-12 form-group">
                            {{form.password.label}}{{form.password(class="form-control")}}
                          </div>
                        </div>
                        {% for error in form.password.errors %}
                        <span style="color: red;">{{ error }}</span>
                        {% endfor %}
                        <div class="row">
                          <div class="col-md-12 form-group">
                            {{form.pass_confirm.label}}{{form.pass_confirm(class="form-control")}}
                          </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 form-group">
                              {{form.channels.label()}}{{form.channels(class="form-control")}}
                            </div>
                          </div> 

                          <div class="row">
                            <div class="col-md-12 form-group">
                              {{form.ip.label()}}{{form.ip(class="form-control")}}
                            </div>
                          </div> 

                          <div class="row">
                            <div class="col-md-12 form-group">
                              {{form.inbound.label()}}{{form.inbound(class="form-control")}}
                            </div>
                          </div> 

                          <div class="row">
                            <div class="col-md-12 form-group">
                              {{form.outbound.label()}}{{form.outbound(class="form-control")}}
                            </div>
                          </div> 

                          <div class="row">
                            <div class="col-md-12 form-group">
                              {{form.provider.label()}}{{form.provider(class="form-control")}}
                            </div>
                          </div> 

                          <div class="row">
                            <div class="col-md-12 form-group">
                              {{form.codecs.label()}}{{form.codecs(class="form-control")}}
                            </div>
                          </div> 

                          <div class="row">
                            <div class="col-md-12 form-group">
                              {{form.certificate.label()}}{{form.certificate(class="form-control")}}
                            </div>
                          </div> 
        
                        <div class="row">
                          <div class="col-md-12">
                            {{form.submit(class="btn btn-primary rounded-0 py-2 px-4",style="margin-left: 40%;")}}
                            <span class="submitting"></span>
                          </div>
                        </div>
                      </form>
      
                    <div id="form-message-warning mt-4"></div> 
                    <div id="form-message-success">
                   
                    </div>
      
                  </div>
                  <div class="col-lg-4 ml-auto" style="margin-top: 25%;">
                    <h3 class="mb-4"> Registered?</h3>

                    <p><a class="btn btn-primary rounded-0 py-2 px-4 " style="margin-left: 15%;"  href="{{ url_for('users.login') }}">Sign In</a></p>
                  </div>
                </div>
              </div>  
              </div>
            </div>
        </div>
      
{% endblock %}

structure/templates/socketiotest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Therapy Session</title>
</head>
<body>
    <h1>Therapy Session</h1>
    <button onclick="startMeeting()">Start Meeting</button>
    1:
    <div id="local-video" style="width: 320px; height: 240px;"></div>
    2:
    <div id="therapist-video" style="width: 320px; height: 240px;"></div>
    

    <!-- <script src="https://cdn.agora.io/sdk/release/AgoraRTCSDK-4.0.0.js"></script> -->
    <script src=" https://cdn.jsdelivr.net/npm/agora-rtc-sdk@3.6.11/AgoraRTCSDK.min.js "></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.1.2/socket.io.js"></script>
    <script>
        const agoraAppId = '{{agora_id}}';
        const channelName = 'Udo';
        const uid = Math.floor(Math.random() * 1000000).toString();
        console.log(uid)
        console.log(agoraAppId)

        const socket = io.connect('http://' + document.domain + ':' + location.port);

        const client = AgoraRTC.createClient({ mode: 'rtc', codec: 'h264' });
        client.init(agoraAppId, () => console.log('Agora client initialized successfully'), err => console.error(err));

        function startMeeting() {
            console.log(channelName)
            console.log(uid)
            console.log('trying to start meeting')
            client.join(null, channelName, null, uid, () => console.log('User joined channel successfully'), err => console.error(err));
            console.log("still working..")
            navigator.mediaDevices.getUserMedia({ video: true, audio: true })
            .then(stream => {
                console.log('Local media access granted:', stream);

                const localStream = AgoraRTC.createStream({ streamID: uid, audio: true, video: true, screen: false });
                localStream.init(() => {
                    console.log('Local stream initialized successfully');
                    localStream.play('local-video');
                    client.publish(localStream);

                    console.log('Local stream published successfully');

                    // For simplicity, let's handle therapist logic here too
                    const therapistStream = AgoraRTC.createStream({ streamID: uid, audio: true, video: true, screen: false });
                    therapistStream.init(() => {
                        therapistStream.play('therapist-video');
                        console.log('Therapist stream played successfully');
                    }, err => console.error(err));
                }, err => console.error(err));
            })
            .catch(error => console.error('Error accessing local media:', error));
    }
        //     const localStream = AgoraRTC.createStream({ streamID: uid, audio: true, video: true, screen: false });
        //     localStream.init(() => {
        //         localStream.play('local-video');
        //         client.publish(localStream);
        //     }, err => console.error(err));

        //     socket.emit('join_room', { 'room': channelName });
        // }



//         function startMeeting() {
//             console.log("starting meeting...")
//     // Initialize Agora client for the user
//         client.join(null, channelName, null, uid, () => {
//         console.log('User joined channel successfully');

//         // Access local media
//         navigator.mediaDevices.getUserMedia({ video: true, audio: true })
//             .then(stream => {
//                 const localStream = AgoraRTC.createStream({ streamID: uid, audio: true, video: true, screen: false });
//                 localStream.init(() => {
//                     localStream.play('local-video');
//                     client.publish(localStream);

//                     // Initialize Agora client for the therapist to join
//                     const agoraTherapistClient = AgoraRTC.createClient({ mode: 'rtc', codec: 'h264' });
//                     agoraTherapistClient.init(agoraAppId, () => {
//                         agoraTherapistClient.join(null, channelName, null, () => {
//                             // Handle the therapist joining, play their video, etc.
//                             const therapistVideo = document.createElement('div');
//                             therapistVideo.id = 'therapist-video';
//                             document.body.appendChild(therapistVideo);

//                             const therapistStream = AgoraRTC.createStream({ streamID: uid, audio: true, video: true, screen: false });
//                             therapistStream.init(() => {
//                                 therapistStream.play('therapist-video');
//                             }, err => console.error(err));
//                         }, err => console.error(err));
//                     }, err => console.error(err));
//                 }, err => console.error(err));
//             })
//             .catch(error => console.error('Error accessing local media:', error));
//     }, err => console.error(err));
// }
        // socket.on('joined_room', data => {
        //     console.log('Joined room:', data.room);
        //     // Provide the clients with the link to join the meeting
        //     // You can use this information to generate unique meeting links for clients
        // });


//         function startMeeting() {
//     console.log("starting meeting...");

//     client.join(null, channelName, null, uid, (uid) => {
//         console.log('User joined channel successfully with UID:', uid);

//         navigator.mediaDevices.getUserMedia({ video: true, audio: true })
//             .then(stream => {
//                 console.log('Local media access granted:', stream);

//                 const localStream = AgoraRTC.createStream({ streamID: uid, audio: true, video: true, screen: false });
//                 localStream.init(() => {
//                     localStream.play('local-video');
//                     client.publish(localStream);

//                     console.log('Local stream published successfully');

//                     // For simplicity, let's handle therapist logic here too
//                     const therapistStream = AgoraRTC.createStream({ streamID: uid, audio: true, video: true, screen: false });
//                     therapistStream.init(() => {
//                         therapistStream.play('therapist-video');
//                         console.log('Therapist stream played successfully');
//                     }, err => console.error(err));
//                 }, err => console.error(err));
//             })
//             .catch(error => console.error('Error accessing local media:', error));
//     }, err => console.error(err));
// }
    </script>
</body>
</html>